# Generated by Django 3.0.7 on 2020-06-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200616_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='amount',
        ),
    ]
