# Generated by Django 3.0.7 on 2020-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='anonymousId',
            new_name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('shopping', 'SHOPPING'), ('checkout', 'CHECKOUT'), ('paid', 'PAID'), ('cancelled', 'CANCELLED')], default='shopping', max_length=200),
        ),
    ]
