# Generated by Django 3.0.7 on 2020-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200627_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
