# Generated by Django 3.0.7 on 2020-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200825_1853'),
        ('cart', '0012_auto_20200629_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_cart_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
