# Generated by Django 3.0.7 on 2020-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200825_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='anonymous_cart_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='anonymous_cart_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
