# Generated by Django 3.0.7 on 2020-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200825_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='anonymous_cart_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
