# Generated by Django 3.0.7 on 2020-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
