# Generated by Django 3.0.7 on 2020-06-12 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200612_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 12, 18, 15, 46, 60336, tzinfo=utc)),
        ),
    ]
