# Generated by Django 3.0.7 on 2020-06-12 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200612_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 12, 22, 6, 45, 959832, tzinfo=utc)),
        ),
    ]
