# Generated by Django 3.0.7 on 2020-06-18 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200616_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 18, 14, 17, 12, 467959, tzinfo=utc)),
        ),
    ]
