# Generated by Django 3.0.7 on 2020-06-21 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200621_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 14, 0, 22, 327157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_type',
            field=models.CharField(blank=True, help_text='this could be a different colour, size,or more things out of the box', max_length=200, verbose_name='type'),
        ),
    ]
