# Generated by Django 3.0.7 on 2020-06-21 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200621_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagecontent',
            options={'verbose_name': 'Package Content', 'verbose_name_plural': 'Package Content'},
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 21, 14, 15, 25, 264885, tzinfo=utc)),
        ),
    ]
