# Generated by Django 3.0.7 on 2020-06-22 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200621_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagecontent',
            old_name='name',
            new_name='package',
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 9, 3, 53, 561168, tzinfo=utc)),
        ),
    ]
