# Generated by Django 3.0.7 on 2020-06-22 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200622_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 9, 22, 14, 23838, tzinfo=utc)),
        ),
    ]
