# Generated by Django 3.0.7 on 2020-06-22 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200622_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 9, 25, 22, 582463, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='packagecontent',
            constraint=models.UniqueConstraint(fields=('package', 'product'), name='unique_packaged_product'),
        ),
    ]
