# Generated by Django 3.0.7 on 2020-06-25 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200622_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 17, 57, 3, 546839, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProductAddons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='products.Product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_add_ons', to='products.ProductVariation')),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
            },
        ),
        migrations.AddConstraint(
            model_name='productaddons',
            constraint=models.UniqueConstraint(fields=('product_type', 'product'), name='unique_combination'),
        ),
    ]
