# Generated by Django 3.0.7 on 2020-06-25 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200625_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 18, 39, 36, 179698, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 18, 39, 36, 142900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productaddons',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
