# Generated by Django 3.0.7 on 2020-06-25 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200625_1939'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productaddons',
            name='unique_combination',
        ),
        migrations.RemoveField(
            model_name='productaddons',
            name='product',
        ),
        migrations.AddField(
            model_name='productaddons',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.FoodItem'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 18, 57, 6, 954700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 18, 57, 6, 825189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productaddons',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='products.ProductVariation'),
        ),
        migrations.AddConstraint(
            model_name='productaddons',
            constraint=models.UniqueConstraint(fields=('product_type', 'food_item'), name='unique_combination'),
        ),
    ]
