# Generated by Django 3.0.7 on 2020-06-26 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200625_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAddons',
            new_name='ProductAddon',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 7, 13, 15, 578034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 7, 13, 15, 544320, tzinfo=utc)),
        ),
    ]
