# Generated by Django 3.0.7 on 2020-06-26 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200626_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonitem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 11, 24, 49, 68398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 11, 24, 49, 39450, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='productaddon',
            constraint=models.UniqueConstraint(fields=('product_type', 'add_on_item'), name='unique_combination'),
        ),
    ]
