# Generated by Django 3.0.7 on 2020-08-25 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200825_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonitem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 25, 19, 28, 15, 614399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 25, 19, 28, 15, 546465, tzinfo=utc)),
        ),
    ]
